In [10]:
import pandas as pd

In [14]:
df = pd.DataFrame({
    "Department":["HR","HR","IT","IT","Marketing","Marketing","Sales","Sales"],
    "Team":["A","A","B","B","C","C","D","D"],
    "Gender":["M","F","M","F","M","F","M","F"],
    "Salary":[85,90,78,85,92,88,75,80],
    "Age":[23,25,30,22,28,26,21,27],
    "JoinDate":pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20","2021-04-10",
        "2020-05-30", "2020-06-25" , "2021-07-15", "2021-08-01"    
    ]) 
})

In [35]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

#### How you can use these common Aggregation func. with group buy

In [16]:
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [17]:
type(df.groupby("Department")["Salary"].mean())

pandas.core.series.Series

In [18]:
df.groupby("Team")["Salary"].sum()

Team
A    175
B    163
C    180
D    155
Name: Salary, dtype: int64

In [19]:
df.groupby("Team")["Salary"].count()

Team
A    2
B    2
C    2
D    2
Name: Salary, dtype: int64

In [22]:
df.groupby("Department")["Salary"].min()

Department
HR           85
IT           78
Marketing    88
Sales        75
Name: Salary, dtype: int64

In [23]:
df.groupby("Department")["Salary"].max()

Department
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [24]:
df.groupby("Department")["Salary"].count()

Department
HR           2
IT           2
Marketing    2
Sales        2
Name: Salary, dtype: int64

#### AGG and Aggregation function in pandas they are exactly same.

In [31]:
df.groupby("Team")["Salary"].agg(["mean","max","min"])

      mean  max  min
Team
A     87.5   90   85
B     81.5   85   78
C     90.0   92   88
D     77.5   80   75

#### This is not series, this is a data frame. it's output is a data frame.

In [32]:
type(df.groupby("Team")["Salary"].agg(["mean","max","min"]))

pandas.core.frame.DataFrame

#### If you want that the name of my column is of my choice, then you run something like this.
--> your column name will be of your choice.

In [34]:
df.groupby("Team")["Salary"].aggregate(
    avg_score = "mean",
    high_score = "max"
)

      avg_score  high_score
Team
A          87.5          90
B          81.5          85
C          90.0          92
D          77.5          80

In [36]:
df["Team Avg"] = df.groupby("Team")["Salary"].transform("mean")

In [37]:
df

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [39]:
df.groupby("Team").filter(lambda x : x["Salary"].mean()>85)

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0