In [10]:
import pandas as pd

In [118]:
df = pd.read_csv("data_2.csv")

In [119]:
df

        Actor     Film  Year        Genre  BoxOffice  IMDb
0  Alia Bhutt     Deva  2023      Commedy       1050   7.2
1        Sita  Ramayan  2017  Inspiration        565   6.0
2  Mandoddari  Ramayan  2016  Inspiration       2024   8.4
3      Ahalya  Ramayan  2022       Action        431   5.6
4    sabribai  Ramayan  2018       Action        585   7.0
5       Radha  Krishna  2005  Inspiration        111   8.3
6       Ganga  Aeknath  1985  Inspiration        180   7.5
7     Urminla  Ramayan  1980       Action        475   5.5
8    kashlaya  Ramayan  2000  Inspiration        318   6.2

In [120]:
df['Actor']

0    Alia Bhutt
1          Sita
2    Mandoddari
3        Ahalya
4      sabribai
5         Radha
6         Ganga
7       Urminla
8      kashlaya
Name: Actor, dtype: object

In [121]:
type(df['Actor'])

pandas.core.series.Series

In [122]:
df[['Actor','Year','Genre']]

        Actor  Year        Genre
0  Alia Bhutt  2023      Commedy
1        Sita  2017  Inspiration
2  Mandoddari  2016  Inspiration
3      Ahalya  2022       Action
4    sabribai  2018       Action
5       Radha  2005  Inspiration
6       Ganga  1985  Inspiration
7     Urminla  1980       Action
8    kashlaya  2000  Inspiration

In [143]:
df.loc[0] # Whenever we change our row lables 0,1,2,3...,A,B,C,D this one 
will find by row labels

SyntaxError: invalid syntax (185952925.py, line 2)

In [124]:
df.iloc[1] # Whenever we change our row lables,in this row labels 0,1,2,3... instead A,B,C,D... this one will find by index position.

Actor               Sita
Film             Ramayan
Year                2017
Genre        Inspiration
BoxOffice            565
IMDb                 6.0
Name: 1, dtype: object

#### Using loc --> I can locate any cell by doing df.loc

In [126]:
df.loc[8,'IMDb']

np.float64(6.2)

In [127]:
df.loc[6,'Actor']

'Ganga'

### Usind iloc [index position]
#### --> The ilog means that the value of i Will be used.
#### --> The value of i Always start from 0 if you have read loops from python.

In [128]:
df.iloc[8,5] # df.loc[8,'IMDb'] --> same as this diff only 'IMDB' instead index position 5

np.float64(6.2)

#### What is the diffrence?
--> We use labels in loc and in ilog We use indices which start from 0.

#### you can do slicing by using loc and ilog.

In [129]:
df.loc[0:2 ,['Actor', 'Year','Film']] # last index as inclusive.

        Actor  Year     Film
0  Alia Bhutt  2023     Deva
1        Sita  2017  Ramayan
2  Mandoddari  2016  Ramayan

In [130]:
df.iloc[0:2 ,[0,2,3]] # last index as exclusive.

        Actor  Year        Genre
0  Alia Bhutt  2023      Commedy
1        Sita  2017  Inspiration

#### --> Using loc and iloc function you can get Particular range when it comes to row and columns.

### Using at and iat method

### To access a Particular element. and this is the fastest method. it gives you fast access to a particular element.

In [131]:
df.at[0,'Film']

'Deva'

In [132]:
df.iat[0,1] # df.at[0,'Film']--> same as this diff only 'Film' instead index position 1

'Deva'

#### Note:- The at and iat are optimized for just  access only one element.
--> it is only for element access. to access a particular cell.

In [133]:
df[df['IMDb']>6]

        Actor     Film  Year        Genre  BoxOffice  IMDb
0  Alia Bhutt     Deva  2023      Commedy       1050   7.2
2  Mandoddari  Ramayan  2016  Inspiration       2024   8.4
4    sabribai  Ramayan  2018       Action        585   7.0
5       Radha  Krishna  2005  Inspiration        111   8.3
6       Ganga  Aeknath  1985  Inspiration        180   7.5
8    kashlaya  Ramayan  2000  Inspiration        318   6.2

In [134]:
df[(df['IMDb']>6) & (df['Year']>2018)]

        Actor  Film  Year    Genre  BoxOffice  IMDb
0  Alia Bhutt  Deva  2023  Commedy       1050   7.2

In [135]:
df[(df['IMDb']>6) | (df['Year']>2018)]

        Actor     Film  Year        Genre  BoxOffice  IMDb
0  Alia Bhutt     Deva  2023      Commedy       1050   7.2
2  Mandoddari  Ramayan  2016  Inspiration       2024   8.4
3      Ahalya  Ramayan  2022       Action        431   5.6
4    sabribai  Ramayan  2018       Action        585   7.0
5       Radha  Krishna  2005  Inspiration        111   8.3
6       Ganga  Aeknath  1985  Inspiration        180   7.5
8    kashlaya  Ramayan  2000  Inspiration        318   6.2

In [136]:
df.query("Year>2019")

        Actor     Film  Year    Genre  BoxOffice  IMDb
0  Alia Bhutt     Deva  2023  Commedy       1050   7.2
3      Ahalya  Ramayan  2022   Action        431   5.6

#### Note :- not use [& , | ] sign use [and,or] keyword when use .query method

In [137]:
df.query("Year>2018 and BoxOffice>318")

        Actor     Film  Year    Genre  BoxOffice  IMDb
0  Alia Bhutt     Deva  2023  Commedy       1050   7.2
3      Ahalya  Ramayan  2022   Action        431   5.6

#### Note :- Pandas never gurantee that you will get a copy, then you use .copy function.
#### --> Don't get confused about whether the view is coming or the copy is coming 
--> Don't remember when the view is returning yaa coppy copy is returning.
--> copy ke sath kam karna hai to copy method use karo
--> use .copy method is a guarantee that df2 is a copy. it will not modify df.

In [151]:
df2 = df[['Actor','IMDb']].copy()

In [152]:
df2

        Actor  IMDb
0  Alia Bhutt   7.2
1        Sita   6.0
2  Mandoddari   8.4
3      Ahalya   5.6
4    sabribai   7.0
5       Radha   8.3
6       Ganga   7.5
7     Urminla   5.5
8    kashlaya   6.2

In [153]:
df2.loc[0,'Actor'] = 'Harry'

In [154]:
df2

        Actor  IMDb
0       Harry   7.2
1        Sita   6.0
2  Mandoddari   8.4
3      Ahalya   5.6
4    sabribai   7.0
5       Radha   8.3
6       Ganga   7.5
7     Urminla   5.5
8    kashlaya   6.2

In [155]:
df

        Actor     Film  Year        Genre  BoxOffice  IMDb
0  Alia Bhutt     Deva  2023      Commedy       1050   7.2
1        Sita  Ramayan  2017  Inspiration        565   6.0
2  Mandoddari  Ramayan  2016  Inspiration       2024   8.4
3      Ahalya  Ramayan  2022       Action        431   5.6
4    sabribai  Ramayan  2018       Action        585   7.0
5       Radha  Krishna  2005  Inspiration        111   8.3
6       Ganga  Aeknath  1985  Inspiration        180   7.5
7     Urminla  Ramayan  1980       Action        475   5.5
8    kashlaya  Ramayan  2000  Inspiration        318   6.2