In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data_cleaning_sample.csv")

In [4]:
df

      Name   Age      City Gender               Email    JoinDate
0     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna  21.0     Surat      M  Krishna4@gmail.com  15/06/2020
2   Khushi   NaN     Delhi      F   Khushi1@gmail.com  20/07/2021
3     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
4      NaN  22.0  Banglore      M      Shrut@gmal.com         NaN
5     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019

In [5]:
df.isnull()

    Name    Age   City  Gender  Email  JoinDate
0  False  False  False   False  False     False
1  False  False  False   False  False     False
2  False   True  False   False  False     False
3  False  False  False   False  False     False
4   True  False  False   False  False      True
5  False  False  False   False  False     False
6  False  False  False   False  False     False
7  False  False  False   False  False     False

In [6]:
df.isnull().sum()

Name        1
Age         1
City        0
Gender      0
Email       0
JoinDate    1
dtype: int64

In [7]:
df.dropna()

      Name   Age      City Gender               Email    JoinDate
0     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna  21.0     Surat      M  Krishna4@gmail.com  15/06/2020
3     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
5     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019

In [8]:
df.dropna(axis=1)

       City Gender               Email
0  New York      F    Jenu54@gmail.com
1     Surat      M  Krishna4@gmail.com
2     Delhi      F   Khushi1@gmail.com
3    Mumbai      F      Metu@gmail.com
4  Banglore      M      Shrut@gmal.com
5  New York      F    Jenu54@gmail.com
6    Mumbai      F      Metu@gmail.com
7    Mumbai      F      Metu@gmail.com

In [9]:
df.fillna(0)

      Name   Age      City Gender               Email    JoinDate
0     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna  21.0     Surat      M  Krishna4@gmail.com  15/06/2020
2   Khushi   0.0     Delhi      F   Khushi1@gmail.com  20/07/2021
3     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
4        0  22.0  Banglore      M      Shrut@gmal.com           0
5     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019

#### replace Missing value with the average

In [10]:
df["Age"].fillna(df["Age"].mean())

0    20.0
1    21.0
2    20.0
3    19.0
4    22.0
5    20.0
6    19.0
7    19.0
Name: Age, dtype: float64

In [11]:
df.ffill()

      Name   Age      City Gender               Email    JoinDate
0     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna  21.0     Surat      M  Krishna4@gmail.com  15/06/2020
2   Khushi  21.0     Delhi      F   Khushi1@gmail.com  20/07/2021
3     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
4     Metu  22.0  Banglore      M      Shrut@gmal.com  12/11/2019
5     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019

In [12]:
df.bfill()

      Name   Age      City Gender               Email    JoinDate
0     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna  21.0     Surat      M  Krishna4@gmail.com  15/06/2020
2   Khushi  19.0     Delhi      F   Khushi1@gmail.com  20/07/2021
3     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
4     Jenu  22.0  Banglore      M      Shrut@gmal.com    1/5/2021
5     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019

In [13]:
df1 = pd.read_csv("data_cleaning_sample.csv")

In [14]:
df1

      Name   Age      City Gender               Email    JoinDate
0     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna  21.0     Surat      M  Krishna4@gmail.com  15/06/2020
2   Khushi   NaN     Delhi      F   Khushi1@gmail.com  20/07/2021
3     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
4      NaN  22.0  Banglore      M      Shrut@gmal.com         NaN
5     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019

In [15]:
df1.duplicated() # Check row wise

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
dtype: bool

In [16]:
df1.drop_duplicates() # remove duplicate row

      Name   Age      City Gender               Email    JoinDate
0     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna  21.0     Surat      M  Krishna4@gmail.com  15/06/2020
2   Khushi   NaN     Delhi      F   Khushi1@gmail.com  20/07/2021
3     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
4      NaN  22.0  Banglore      M      Shrut@gmal.com         NaN

In [17]:
df1.duplicated(subset=["Name","Age"]) # check particular column and return this.

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
dtype: bool

In [18]:
df1["Name"].str.lower()

0       jenu
1    krishna
2     khushi
3       metu
4        NaN
5       jenu
6       metu
7       metu
Name: Name, dtype: object

In [19]:
df1["City"].str.contains("mumbai",case=False)

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
Name: City, dtype: bool

#### Note:
--> In the dataframe, never store python objects.

-->If you want optimized memory allocation and optimized speed.

In [20]:
df["Email"].str.split("@")# This is storing a python list.

0      [Jenu54, gmail.com]
1    [Krishna4, gmail.com]
2     [Khushi1, gmail.com]
3        [Metu, gmail.com]
4        [Shrut, gmal.com]
5      [Jenu54, gmail.com]
6        [Metu, gmail.com]
7        [Metu, gmail.com]
Name: Email, dtype: object

In [21]:
type(df["Email"].str.split("@")[0])

list

In [22]:
df2 = df.dropna().copy()

In [23]:
df2

      Name   Age      City Gender               Email    JoinDate
0     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna  21.0     Surat      M  Krishna4@gmail.com  15/06/2020
3     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
5     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019

In [24]:
df2["Age"] = df2["Age"].astype(int)

In [25]:
df2

      Name  Age      City Gender               Email    JoinDate
0     Jenu   20  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna   21     Surat      M  Krishna4@gmail.com  15/06/2020
3     Metu   19    Mumbai      F      Metu@gmail.com  12/11/2019
5     Jenu   20  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu   19    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu   19    Mumbai      F      Metu@gmail.com  12/11/2019

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Age       6 non-null      int64
 2   City      6 non-null      object
 3   Gender    6 non-null      object
 4   Email     6 non-null      object
 5   JoinDate  6 non-null      object
dtypes: int64(1), object(5)
memory usage: 336.0+ bytes

In [28]:
df2

      Name  Age      City Gender               Email    JoinDate
0     Jenu   20  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna   21     Surat      M  Krishna4@gmail.com  15/06/2020
3     Metu   19    Mumbai      F      Metu@gmail.com  12/11/2019
5     Jenu   20  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu   19    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu   19    Mumbai      F      Metu@gmail.com  12/11/2019

In [34]:
df

      Name   Age      City Gender               Email    JoinDate
0     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
1  Krishna  21.0     Surat      M  Krishna4@gmail.com  15/06/2020
2   Khushi   NaN     Delhi      F   Khushi1@gmail.com  20/07/2021
3     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
4      NaN  22.0  Banglore      M      Shrut@gmal.com         NaN
5     Jenu  20.0  New York      F    Jenu54@gmail.com    1/5/2021
6     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019
7     Metu  19.0    Mumbai      F      Metu@gmail.com  12/11/2019

In [35]:
# 1st type
# df2["Age group"]= df2["Age"].apply(lambda x : "Adult" if x >= 20 else "Minor")
# 2nd type
def isminor(x):
    return "Adult" if x >= 20 else "Minor"
df2["Age group"] = df2["Age"].apply(isminor)

In [30]:
df2

      Name  Age      City Gender               Email    JoinDate Age group
0     Jenu   20  New York      F    Jenu54@gmail.com    1/5/2021     Adult
1  Krishna   21     Surat      M  Krishna4@gmail.com  15/06/2020     Adult
3     Metu   19    Mumbai      F      Metu@gmail.com  12/11/2019     Minor
5     Jenu   20  New York      F    Jenu54@gmail.com    1/5/2021     Adult
6     Metu   19    Mumbai      F      Metu@gmail.com  12/11/2019     Minor
7     Metu   19    Mumbai      F      Metu@gmail.com  12/11/2019     Minor

In [32]:
gender_map = {"M":"Male" , "F":"Female" , "O":"Other"}
df2["Gender"]= df2["Gender"].map(gender_map)

In [33]:
df2

      Name  Age      City  Gender               Email    JoinDate Age group
0     Jenu   20  New York  Female    Jenu54@gmail.com    1/5/2021     Adult
1  Krishna   21     Surat    Male  Krishna4@gmail.com  15/06/2020     Adult
3     Metu   19    Mumbai  Female      Metu@gmail.com  12/11/2019     Minor
5     Jenu   20  New York  Female    Jenu54@gmail.com    1/5/2021     Adult
6     Metu   19    Mumbai  Female      Metu@gmail.com  12/11/2019     Minor
7     Metu   19    Mumbai  Female      Metu@gmail.com  12/11/2019     Minor

In [39]:
df2["City"] = df2["City"].replace({"Mumbai":"New Mumbai","Surat":"New surat"})

In [40]:
df2

      Name  Age        City  Gender               Email    JoinDate Age group
0     Jenu   20    New York  Female    Jenu54@gmail.com    1/5/2021     Adult
1  Krishna   21   New surat    Male  Krishna4@gmail.com  15/06/2020     Adult
3     Metu   19  New Mumbai  Female      Metu@gmail.com  12/11/2019     Minor
5     Jenu   20    New York  Female    Jenu54@gmail.com    1/5/2021     Adult
6     Metu   19  New Mumbai  Female      Metu@gmail.com  12/11/2019     Minor
7     Metu   19  New Mumbai  Female      Metu@gmail.com  12/11/2019     Minor